django_project/django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from posts.views import home_view, CreateCrush, tagged, PostUpdateView, PostDeleteView, PostDetailView
from landing.views import landing_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_home, name='landing-home'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('crush/', home_view, name='crush'),
    path('crush/create/', CreateCrush, name="create-crush"),
    path('crush/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('crush/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tag/<slug:slug>/', tagged, name="tagged"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
# from users import views as user_views
from landing.views import landing_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_home, name='landing-home'),
    path('', include('allauth.urls')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='crushes')),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    

]

# During development, you can access user-uploaded images using MEDIA_ROOT, but after production it checks MEDIA_URL  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (
	crush,
	tagged,
	statistics,
	CreateCrush, 
	PostUpdateView, 
	PostDeleteView, 
	PostDetailView
	)
# We feed in the methods which has the logic, and then it goes to html pages
# We now create a path where the html page will be displayed
urlpatterns = [
	path('crush/', crush, name='crush'),
	path('crush/create/', CreateCrush, name="create-crush"),
	path('crush/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
	path('crush/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	# path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('tag/<slug:slug>/', tagged, name="tagged"),
	path('crush/statistics', statistics, name='statistics'),

]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render

#Logic for landing page only an html file
def landing_home(request):
    return render(request, 'landing/landing.html')

landing/templates/landing/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Krush | Keep track of your crushes</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.css">
	<script src="https://kit.fontawesome.com/f1a03565c4.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
	<header class="site-navbar site-navbar-target" role="banner">
	      <nav class="site-navigation navbar navbar-expand-md navbar-light">
	        <div class="container">
	          <div class="col-7 col-md-3 col-xl-4  d-block">
						<h1 class="mb-0 site-logo"><a href="{% url 'landing-home' %}" class="text-black h2 mb-0">Krush<span class="text-primary">.</span> </a></h1>
			   </div>
	          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	          </button>
	          <div class="collapse navbar-collapse" id="navbarToggle">
	            <div class="navbar-nav mr-auto"></div>
	            <!-- Navbar Right Side -->
	            {% if user.is_authenticated %}
		            <div class="site-menu navbar-nav">
		            	<li><a class="nav-link" href="/crush">Dashboard</a></li>
		            	<li><a class="nav-link" href="/crush/create">Create Crush</a></li>   
					    <li><a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a></li>
					    <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
		            </div>
		        {% else %}
		        	<div class="site-menu navbar-nav">
		        		<li><a class="nav-item nav-link" href="{% url 'account_login' %}">Login</a></li>		     
					    <li><a class="nav-item nav-link" href="/signup">Register</a></li>
					     
		            </div>
		        {% endif %}

	          </div>
	        </div>
	      </nav>
	</header>
	{% block content %}{% endblock content %}

	<!--Footer-->
	<div class="footer py-5 text-center">
		<div class="container">
			<div class="row mb-5">
				<div class="col-12">
					<p class="mb-0">
						<a href="#" class="p-3"><span><i class="fab fa-facebook"></i></span></a>
						<a href="#" class="p-3"><span><i class="fab fa-twitter"></i></span></a>
						<a href="#" class="p-3"><span><i class="fab fa-instagram"></i></span></a>
						<a href="#" class="p-3"><span><i class="fab fa-linkedin"></i></span></a>
					</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<p class="mb-0">
						Copyright &copy;<script type="232c8fa1d69ab1b850676250-text/javascript">document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fas fa-heart text-danger"></i></i> by <a href="https://www.linkedin.com/in/fzchriha/" target="_blank">Fatima Zahra Chriha</a>
					</p>
				</div>
			</div>
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" type="232c8fa1d69ab1b850676250-text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.min.js" type="232c8fa1d69ab1b850676250-text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.min.js" type="232c8fa1d69ab1b850676250-text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" type="232c8fa1d69ab1b850676250-text/javascript"></script>
	<script src="{% static 'js/main.js' %}" type="232c8fa1d69ab1b850676250-text/javascript"></script>
	<script type="232c8fa1d69ab1b850676250-text/javascript">
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>
	<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="232c8fa1d69ab1b850676250-|49" defer=""></script>

</body>
</html>

landing/templates/landing/base_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Krush | Login</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

<script src="https://kit.fontawesome.com/f1a03565c4.js" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.0/animate.min.css">

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/css/animsition.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

<link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body style="background-color: #fff;">
	
	{% block content %}{% endblock content %}

	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/js/animsition.min.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

	<script src="vendor/select2/select2.min.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>

	<script src="vendor/daterangepicker/moment.min.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>
	<script src="vendor/daterangepicker/daterangepicker.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>

	<script src="vendor/countdowntime/countdowntime.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>

	<script src="js/main.js" type="1f950a75b69094ddd505f6d9-text/javascript"></script>

	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="1f950a75b69094ddd505f6d9-text/javascript"></script>
	<script type="1f950a75b69094ddd505f6d9-text/javascript">
	      window.dataLayer = window.dataLayer || [];
	      function gtag(){dataLayer.push(arguments);}
	      gtag('js', new Date());

	      gtag('config', 'UA-23581568-13');
	    </script>
	<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="1f950a75b69094ddd505f6d9-|49" defer=""></script></body>
	</html>

</body>
</html>

landing/templates/landing/landing.html
{% extends "landing/base.html" %}
{% load static %}
{% block content %}
		<div class="site-blocks-cover" style="overflow: hidden;">
			<div class="container">
				<div class="row align-items-center justify-content-center">
					<div class="col-md-12" style="position: relative;" data-aos="fade-up" data-aos-delay="200">
						<img src="{% static 'media/people.png' %}" alt="Image" class="img-absolute">
						<div class="row mb-4" data-aos="fade-up" data-aos-delay="200">
							<div class="col-lg-6 mr-auto">
								<h1>Keep Your Crushes Counted</h1>
								<p class="mb-5">Keep confusing your friends with the numerous crushes you have? Use Krush so you can keep a record of them and share it with your friends, *Bonus* you get to understand what attracts you!.</p>
								<div>
									<a href="/signup" class="btn btn-primary mr-2 mb-2">Get Started</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="site-section" id="features-section">
			<div class="container">
				<div class="row mb-5 justify-content-center text-center" data-aos="fade-up">
					<div class="col-7 text-center  mb-5">
						<h2 class="section-title">Krush Features</h2>
						<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga quos quaerat sapiente nam, id vero.</p>
					</div>
				</div>
				<div class="row align-items-stretch">
					<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">
						<div class="unit-4 d-block">
							<div class="unit-4-icon mb-3">
								<span class="icon-wrap"><span class="text-primary"><i class="fas fa-user-friends"></i></span></span>
							</div>
							<div>
								<h3>Connect to Friends</h3>
								<p>Keep your friends updated on whose your new crush</p>
								<p><a href="#">Learn More</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">
						<div class="unit-4 d-block">
							<div class="unit-4-icon mb-3">
								<span class="icon-wrap"><span class="text-primary"><i class="fas fa-clipboard-list"></i></span></span>
							</div>
							<div>
								<h3>Record Journey</h3>
								<p>Keep a record of your crushes from middle school to college and more</p>
								<p><a href="#">Learn More</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-4 mb-4 mb-lg-4" data-aos="fade-up" data-aos-delay="200">
						<div class="unit-4 d-block">
							<div class="unit-4-icon mb-3">
								<span class="icon-wrap"><span class="text-primary"><i class="far fa-chart-bar"></i></span></span>
							</div>
							<div>
								<h3>Analyze Crushes</h3>
								<p>Discover the traits you are most attracted to in your crushes</p>
								<p><a href="#">Learn More</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="feature-big">
			<div class="container">
				<div class="row mb-5 site-section">
					<div class="col-lg-7" data-aos="fade-right">
						<img src="{% static 'media/record-journey.png' %}" alt="Image" class="img-fluid">
					</div>
					<div class="col-lg-5 pl-lg-5 ml-auto mt-md-5">
					<h2 class="text-black">Keep a record of your crushes</h2>
					<p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem neque nisi architecto autem molestias corrupti officia veniam.</p>
						<div class="author-box" data-aos="fade-left">
							<div class="d-flex mb-4">
								<div class="mr-3">
									<!--Add an image here-->
									<!-- <img src="images/person_4.jpg" alt="Image" class="img-fluid rounded-circle"> -->
								</div>
								<div class="mr-auto text-black">
									<strong class="font-weight-bold mb-0">Grey Simpson</strong> <br>
									Co-Founder, XYZ Inc.
								</div>
							</div>
							<blockquote>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus vitae ipsa asperiores inventore aperiam iure?&rdquo;</blockquote>
						</div>
					</div>
				</div>
				<div class="mt-5 row mb-5 site-section ">
					<div class="col-lg-7 order-1 order-lg-2" data-aos="fade-left">
					<img src="{% static 'media/crush-analysis.png' %}" alt="Image" class="img-fluid">
					</div>
					<div class="col-lg-5 pr-lg-5 mr-auto mt-5 order-2 order-lg-1">
					<h2 class="text-black">Understand what attracts you</h2>
					<p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem neque nisi architecto autem molestias corrupti officia veniam</p>
					<div class="author-box" data-aos="fade-right">
					<div class="d-flex mb-4">
					<div class="mr-3">
					<!--Add an image here-->
					<!-- <img src="images/person_1.jpg" alt="Image" class="img-fluid rounded-circle"> -->
					</div>
					<div class="mr-auto text-black">
					<strong class="font-weight-bold mb-0">Kimberly Gush</strong> <br>
					Co-Founder, XYZ Inc.
					</div>
					</div>
					<blockquote>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus vitae ipsa asperiores inventore aperiam iure?&rdquo;</blockquote>
					</div>
					</div>
				</div>
				<div class="row mb-5 site-section">
					<div class="col-lg-7" data-aos="fade-right">
					<img src="{% static 'media/share-friends.png' %}" alt="Image" class="img-fluid">
					</div>
					<div class="col-lg-5 pl-lg-5 ml-auto mt-md-5">
					<h2 class="text-black">Share with friends your latest crush</h2>
					<p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem neque nisi architecto autem molestias corrupti officia veniam.</p>
					<div class="author-box" data-aos="fade-left">
					<div class="d-flex mb-4">
					<div class="mr-3">
					<!--Add an image here-->
					<!-- <img src="images/person_4.jpg" alt="Image" class="img-fluid rounded-circle"> -->
					</div>
					<div class="mr-auto text-black">
					<strong class="font-weight-bold mb-0">Grey Simpson</strong> <br>
					Co-Founder, XYZ Inc.
					 </div>
					</div>
					<blockquote>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus vitae ipsa asperiores inventore aperiam iure?&rdquo;</blockquote>
					</div>
					</div>
				</div>
			</div>
		</div>
		<div class="site-section bg-light" id="about-section">
			<div class="container">
				<div class="row mb-5">
					<div class="col-12 text-center">
						<h2 class="section-title mb-3">About Us</h2>
					</div>
				</div>
				<div class="row mb-5">
					<div class="col-lg-6" data-aos="fade-right">
						<img src="{% static 'media/mission.png' %}" alt="Image" class="img-fluid">
					</div>
					<div class="col-lg-5 ml-auto pl-lg-5">
						<h2 class="text-black mb-4 h3 font-weight-bold">Our Mission</h2>
						<p class="mb-4">Eos cumque optio dolores excepturi rerum temporibus magni recusandae eveniet, totam omnis consectetur maxime quibusdam expedita dolorem dolor nobis dicta labore quaerat esse magnam unde, aperiam delectus! At maiores, itaque.</p>
						<ul class="mb-5 list-unstyled">
							<li><i class="fas fa-check text-success"></i> Laborum enim quasi at modi</li>
							<li><i class="fas fa-check text-success"></i> Ad at tempore</li>
							<li><i class="fas fa-check text-success"></i> Labore quaerat esse</li>
						</ul>
						<p><a href="#" class="btn btn-primary">Learn More</a></p>
					</div>
				</div>
			</div>
		</div>
{% endblock content %}