django_project/django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from posts.views import home_view, CreateCrush, tagged, PostUpdateView, PostDeleteView, PostDetailView
from landing.views import landing_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_home, name='landing-home'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('crush/', home_view, name='crush'),
    path('crush/create/', CreateCrush, name="create-crush"),
    path('crush/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('crush/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tag/<slug:slug>/', tagged, name="tagged"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
# from users import views as user_views
from landing.views import landing_home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_home, name='landing-home'),
    path('', include('allauth.urls')),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='crushes')),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    

]

# During development, you can access user-uploaded images using MEDIA_ROOT, but after production it checks MEDIA_URL  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import (
	crush,
	tagged,
	statistics,
	CreateCrush, 
	PostUpdateView, 
	PostDeleteView, 
	PostDetailView
	)
# We feed in the methods which has the logic, and then it goes to html pages
# We now create a path where the html page will be displayed
urlpatterns = [
	path('crush/', crush, name='crush'),
	path('crush/create/', CreateCrush, name="create-crush"),
	path('crush/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
	path('crush/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
	# path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
	path('tag/<slug:slug>/', tagged, name="tagged"),
	path('crush/statistics', statistics, name='statistics'),

]

posts/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.contrib.auth.models import User


class Post(models.Model):
    name = models.CharField(max_length=250)
    nickname = models.TextField(default="misterieux")
    content = models.TextField()
    published = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100)
    tags = TaggableManager()

    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from .models import Post

# This form is for creating the profile of the crush (name, nickname, content, traits/tags)
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'nickname',
            'content',
            'tags',
        ]

django_project/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import PostForm
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.defaultfilters import slugify
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

@login_required
def home_view(request):
    posts = Post.objects.filter(author=request.user)
    common_tags = Post.tags.most_common()[:4]
    form = PostForm(request.POST)
    if form.is_valid():
        newpost = form.save(commit=False)
        newpost.slug = slugify(newpost.name)
        newpost.save()
        form.save_m2m()
    context = {
        'posts':posts,
        'common_tags':common_tags,
        'form':form,
    }
    return render(request, 'posts/home.html', context)

@login_required
def CreateCrush(request):
    posts = Post.objects.filter(author=request.user)
    common_tags = Post.tags.most_common()[:4]
    form = PostForm(request.POST)
    if form.is_valid():
        form.instance.author = request.user
        newpost = form.save(commit=False)
        newpost.slug = slugify(newpost.name)
        newpost.save()
        form.save_m2m()
    context = {
        'posts':posts,
        'common_tags':common_tags,
        'form':form,
    }
    return render(request, 'posts/create_crush.html', context)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['name', 'nickname', 'content']
    success_url = '/crush'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/crush'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDetailView(DetailView):
    model = Post

@login_required
def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Post.tags.most_common()[:4]
    user_posts = Post.objects.filter(author=request.user)
    posts = Post.objects.filter(tags=tag, author=request.user)
    context = {
        'tag':tag,
        'common_tags':common_tags,
        'posts':posts,
    }
    return render(request, 'posts/home.html', context)

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from users.models import Profile, FriendRequest
from .forms import PostForm
from collections import Counter
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.defaultfilters import slugify
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
# This method displays the crushes in the home page
# PS: even though friend requests are in the context it is not used yet
# I was counting on diplaying crushes in my friends pages if we are friends (feature no added yet)
@login_required
def crush(request):
    posts = Post.objects.filter(author=request.user)
    common_tags = Post.tags.most_common()[:4]
    form = PostForm(request.POST)
    if form.is_valid():
        newpost = form.save(commit=False)
        #generate urls for the posts aka crushes
        newpost.slug = slugify(newpost.name)
        newpost.save()
        form.save_m2m()
    sent_friend_requests = FriendRequest.objects.filter(from_user=request.user)
    rec_friend_requests = FriendRequest.objects.filter(to_user=request.user)
    context = {
        'posts':posts,
        'common_tags':common_tags,
        'form':form,
        'sent_friend_requests': sent_friend_requests,
        'rec_friend_requests': rec_friend_requests
    }
    return render(request, 'posts/home.html', context)

@login_required
def CreateCrush(request):
    posts = Post.objects.filter(author=request.user)
    common_tags = Post.tags.most_common()[:4]
    form = PostForm(request.POST)
    if form.is_valid():
        form.instance.author = request.user
        newpost = form.save(commit=False)
        newpost.slug = slugify(newpost.name)
        newpost.save()
        form.save_m2m()
    context = {
        'posts':posts,
        'common_tags':common_tags,
        'form':form,
    }
    return render(request, 'posts/create_crush.html', context)

# Update the crush's profile
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['name', 'nickname', 'content']
    success_url = '/crush'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

# Delete the crush's profile
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/crush'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDetailView(DetailView):
    model = Post

# Method is used to enable clicking on a specific tag (trait) and it filters the crushes who have that trait
@login_required
def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = Post.tags.most_common()[:4]
    user_posts = Post.objects.filter(author=request.user)
    posts = Post.objects.filter(tags=tag, author=request.user)
    context = {
        'tag':tag,
        'common_tags':common_tags,
        'posts':posts,
    }
    return render(request, 'posts/home.html', context)

# Function to get the analysis of the crushes traits
# Checkout this article I wrote to understand more how the report is generated
# https://medium.com/@fatimazahrachriha/combine-django-taggit-and-chartjs-85de844de30c
def statistics(request):
    traits = Counter()
    crushes =  Post.objects.filter(author=request.user)
    for crush in crushes:
        for trait in crush.tags.names():
            traits[trait] += 1
    context = {
        'traits': dict(traits)
    }
    
    return render(request, 'posts/statistics.html', context)

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Krush - Home </title>

<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tagsinput.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/feed.css'%}">

</head>
<body translate="no">

    <div class="wrapper">
        <div class="sidebar">
            <div class="bg_shadow"></div>
            <div class="sidebar__inner">
                <div class="close">
                <i class="fas fa-times"></i>
                </div>
                <div class="profile_info">
                <div class="profile_img">
                <img class="rounded-circle" src="{{ user.profile.image.url }}" alt="profile_img">
                </div>
                <div class="profile_data">
                <p class="role">{{ user.username }}</p>
                </div>
                </div>
                    <ul class="siderbar_menu">
                        <li><a href="{% url 'crush' %}" class="active">
                        <div class="title"><i class="fas fa-heart"></i> Home</div>
                        </a></li>
                        <li><a href="{% url 'profile' %}">
                        <div class="title"><i class="fas fa-newspaper"></i> Profile</div>
                        </a></li>
                        <li><a href="#">
                        <div class="title"><i class="fas fa-user-friends"></i> Friends</div>
                        </a></li>
                        <li><a href="#">
                        <div class="title"><i class="fas fa-cog"></i> Settings</div>
                        </a></li>
                    </ul>
                    <div><a href="{% url 'create-crush' %}" class="btn">Create Krush</a></div>

            </div>
        </div>
        <div class="main_container">
            
            {% block content %}{% endblock content %}



<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


  <script type="text/javascript" src="{% static 'js/tagsinput.js'%}"></script>
  <script src="{% static 'js/main.js' %}" type="232c8fa1d69ab1b850676250-text/javascript"></script>
  <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="232c8fa1d69ab1b850676250-|49" defer=""></script>
<script id="rendered-js">
$(".hamburger .fas").click(function () {
  $(".wrapper").addClass("active");
});

$(".wrapper .sidebar .close").click(function () {
  $(".wrapper").removeClass("active");
});
//# sourceURL=pen.js
    </script>
</body>
</html>
      

posts/templates/posts/create_crush.html
{% extends 'posts/base.html' %}

{% block content %}
        <div class="top_navbar">
            <div class="hamburger">
            <div class="hamburger__inner">
            <i class="fas fa-bars"></i>
            </div>
            </div>
            <ul class="menu">
                <li><a href="{% url 'crushes:crush' %}" class="active">Crushes</a></li>
                <li><a href="{% url 'crushes:statistics' %}">Statistics</a></li>
                <li><a href="#">About</a></li>
            </ul>
            <ul class="right_bar">
                <li><a href="{% url 'crushes:crush' %}"><i class="fas fa-heart"></i></a></li>
                <li><a href="{% url 'crushes:statistics' %}"><i class="fas fa-chart-bar"></i></a></li>
                <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            </ul>
        </div>
        <div class="container">
            <div class="row mb-1 posts">
                <div class="col-md-8">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" placeholder="Add name">
                        </div>
                        <div class="form-group">
                            <label>Nickname</label>
                            <input type="text" class="form-control" name="nickname" placeholder="Add name">
                        </div>
                        <div class="form-group">
                            <label>Content</label>
                            <textarea type="text" class="form-control" name="content" placeholder="Add content"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Tags</label>
                            <input type="text" data-role="tagsinput" class="form-control" name="tags">
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>    
{% endblock content %}        

posts/templates/posts/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Krush - Home </title>

<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/tagsinput.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/feed.css'%}">

</head>
<body translate="no">

    <div class="wrapper">
        <div class="sidebar">
            <div class="bg_shadow"></div>
            <div class="sidebar__inner">
                <div class="close">
                <i class="fas fa-times"></i>
                </div>
                <div class="profile_info">
                <div class="profile_img">
                <img class="rounded-circle" src="{{ user.profile.image.url }}" alt="profile_img">
                </div>
                <div class="profile_data">
                <p class="role">{{ user.username }}</p>
                </div>
                </div>
                    <ul class="siderbar_menu">
                        <li><a href="{% url 'crush' %}" class="active">
                        <div class="title"><i class="fas fa-heart"></i> Home</div>
                        </a></li>
                        <li><a href="{% url 'profile' %}">
                        <div class="title"><i class="fas fa-newspaper"></i> Profile</div>
                        </a></li>
                        <li><a href="#">
                        <div class="title"><i class="fas fa-user-friends"></i> Friends</div>
                        </a></li>
                        <li><a href="#">
                        <div class="title"><i class="fas fa-cog"></i> Settings</div>
                        </a></li>
                    </ul>
                    <div><a href="{% url 'create-crush' %}" class="btn">Create Krush</a></div>

            </div>
        </div>
        <div class="main_container">
          <div class="top_navbar">
              <div class="hamburger">
              <div class="hamburger__inner">
              <i class="fas fa-bars"></i>
              </div>
              </div>
              <ul class="menu">
                  <li><a href="{% url 'crush' %}" class="active">Crushes</a></li>
                  <li><a href="{% url 'statistics' %}">Statistics</a></li>
                  <li><a href="#">About</a></li>
              </ul>
              <ul class="right_bar">
                <li><a href="{% url 'create-crush' %}"><i class="fas fa-edit"></i></a></li>
                <li><a href="{% url 'statistics' %}"><i class="fas fa-chart-bar"></i></a></li>
                <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
              </ul>
          </div>
          <div class="container">
                                 {% for post in posts %}
                                     <div class="item no-gutters shadow-sm">
                                         <div>
                                             <div>
                                                 <h3 class="my-1"><a class="name" href="{% url 'post-detail' post.id %}">{{post.name}}</a></h3>

                                                 <div style="display:flex">
                                                     {% for tag in post.tags.all %}
                                                     <a href="{% url 'tagged' tag.slug %}" class="mr-1 badge trait-info">#{{ tag }}</a>
                                                     {% endfor %}
                                                 </div>
                                                 <p class="mb-auto">{{post.nickname}}</p>
                                                 <p class="mb-auto">{{post.content}}</p>
                                                 <p class="mb-auto text-muted">{{post.published}}</p>
                                             </div>
                                         </div>
                                     </div>       

                                 {% endfor %}
              </div>
          </div>
        </div>
    </div>
<script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>


  <script type="text/javascript" src="{% static 'js/tagsinput.js'%}"></script>
  <script src="{% static 'js/main.js' %}" type="232c8fa1d69ab1b850676250-text/javascript"></script>
  <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="232c8fa1d69ab1b850676250-|49" defer=""></script>
<script id="rendered-js">
$(".hamburger .fas").click(function () {
  $(".wrapper").addClass("active");
});

$(".wrapper .sidebar .close").click(function () {
  $(".wrapper").removeClass("active");
});
//# sourceURL=pen.js
    </script>
</body>
</html>
        

posts/templates/posts/post_confirm_delete.html
<!--Page not used-->
{% extends "posts/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/post_detail.html
<!--Post to update the crush's profile-->
{% extends 'posts/base.html' %}
{% block content %}
	<div class="container">
		<h2>{{post.name}}</h2>
		{% for tag in post.tags.all %}
		<a href="#" class="badge badge-info" >{{ tag }}</a>
		{% endfor %}
		<p>{{post.nickname}}</p>
		<p>{{post.content}}</p>
		<p>{{post.published}}</p>
		<a class="btn btn-primary mr-2 mb-2" href="/crush/{{post.id}}/update">Update</a>
	</div>
{% endblock content %}        

posts/templates/posts/post_form.html
<!--Not using this page currently-->
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Crush Profile</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/statistics.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="top_navbar">
        <div class="hamburger">
        <div class="hamburger__inner">
        <i class="fas fa-bars"></i>
        </div>
        </div>
        <ul class="menu">
            <li><a href="{% url 'crushes:crush' %}" >Crushes</a></li>
            <li><a href="{% url 'crushes:statistics' %}" class="active">Statistics</a></li>
            <li><a href="#">About</a></li>
        </ul>
        <ul class="right_bar">
            <li><a href="{% url 'crushes:crush' %}"><i class="fas fa-heart"></i></a></li>
                <li><a href="{% url 'crushes:create-crush' %}"><i class="fas fa-edit"></i></a></li>
                <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
        </ul>
    </div>
    <div class="container">
      <div class="row mb-1 posts">
        <div class="col-md-8">
          <canvas id="myChart" width="400px" height="400px"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
<script type="text/javascript">
  {% block jquery %}
  var crush_traits = {{ traits|safe }};
  var traits = [];
  var repetition = [];
  for (var key in crush_traits) {
    if (crush_traits.hasOwnProperty(key)) {
        traits.push(key);
        repetition.push(crush_traits[key]);
    }
}
  var ctx = document.getElementById('myChart').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: traits,
          datasets: [{
              label: '# of Votes',
              data: repetition,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(153, 102, 255, 0.2)',
                  'rgba(255, 159, 64, 0.2)'
              ],
              borderColor: [
                  'rgba(255, 99, 132, 1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero: true
                  }
              }]
          }
      }
  });

  {% endblock %}  
</script>

{% endblock content %}        